### ISSUE TITLE
test

### ISSUE THREAD

**Issue by ChuckNorrisRR** [organizacaodesoftware/booktrading#2]
gostei da frase anterior

**Comment by NRCEstudante** [comment]
parece funcionar 
![53480650_2400492043515999_4248303129163988992_n](https://user-images.githubusercontent.com/48611246/54470842-e5085480-478d-11e9-8346-71c23c83ecfa.jpg)

**Comment by NRCEstudante** [comment]
viu tem um negocio muito elgal que é tipo vc usar MENOS, Abre CHAVES e fecha CHAVES ele cria um bangzinho dahora

- [ ] bolar um baseado em fatos reais
- [ ] acender a bomba vietnamita
- [ ] viajar pakas
dai da pra assinalar

**Comment by NRCEstudante** [comment]
[New Text Document.txt](https://github.com/organizacaodesoftware/booktrading/files/2975262/New.Text.Document.txt)

**Comment by NRCEstudante** [comment]
ele não aceitar .rar só aceita .zip
[quando-os-e-u-a-descobrem-que-tem-petroleo-em-um-pais-22876236.zip](https://github.com/organizacaodesoftware/booktrading/files/2975265/quando-os-e-u-a-descobrem-que-tem-petroleo-em-um-pais-22876236.zip)
