### ISSUE TITLE
Filmes pra assitir

### ISSUE THREAD

**Issue by NRCEstudante** [organizacaodesoftware/booktrading#3]
vê se você consegue editar esse post e criar novos quadradinhos

> - [ ] tarefa 1
> - [x] tarefa 2
> - [x] tarefa 3
> - [x] tarefa 4
> - [ ] tarefa 5 

![01e2eb06e3bea4a4a4464c84f264d307](https://user-images.githubusercontent.com/48611246/54470996-2ef23a00-4790-11e9-8c29-eddc0026c278.jpg)
![29po5l](https://user-images.githubusercontent.com/48611246/54470997-31549400-4790-11e9-84ea-bccf7410f245.jpg)
![54f57e8419bcb](https://user-images.githubusercontent.com/48611246/54470998-331e5780-4790-11e9-84be-8b4b35a5c195.jpeg)
`algoritmo
var
cacetinho : inteiro
inicio
cacetinho <- 5 - 4
escreva(cacetinho)
fimalgoritmo`

@NRCEstudante

**Comment by ChuckNorrisRR** [comment]
> vê se você consegue editar esse post e criar novos quadradinhos
> 
> > * [x]  tarefa 1
> > * [x]  tarefa 2
> > * [x]  tarefa 3
> > * [x]  tarefa 4
> > * [x ]  tarefa 5
> > * [] tarefa 6
> ![01e2eb06e3bea4a4a4464c84f264d307](https://user-images.githubusercontent.com/48611246/54470996-2ef23a00-4790-11e9-8c29-eddc0026c278.jpg)
> ![29po5l](https://user-images.githubusercontent.com/48611246/54470997-31549400-4790-11e9-84ea-bccf7410f245.jpg)
> ![54f57e8419bcb](https://user-images.githubusercontent.com/48611246/54470998-331e5780-4790-11e9-84be-8b4b35a5c195.jpeg)
> `algoritmo var cacetinho : inteiro inicio cacetinho <- 5 - 4 escreva(cacetinho) fimalgoritmo`
> 
> @NRCEstudante
só vai dar pra fazer assim eu acho, n tem como eu editar
